openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /search:
    post:
      tags:
      - search
      summary: Search
      operationId: search_search_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Search Search Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /user/ping:
    get:
      tags:
      - user
      summary: User Ping
      operationId: user_ping_user_ping_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /user/preferences/extract:
    post:
      tags:
      - user
      summary: Preferences Extract
      operationId: preferences_extract_user_preferences_extract_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreferenceExtractRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Preferences Extract User Preferences Extract Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /user/garments/refresh-description:
    post:
      tags:
      - user
      summary: Refresh Description
      operationId: refresh_description_user_garments_refresh_description_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshDescriptionRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Refresh Description User Garments Refresh Description
                  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inventory/upload:
    post:
      tags:
      - inventory
      summary: Inventory Upload
      operationId: inventory_upload_inventory_upload_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryUploadRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Inventory Upload Inventory Upload Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inventory/batch-upload:
    post:
      tags:
      - inventory
      summary: Inventory Batch Upload
      operationId: inventory_batch_upload_inventory_batch_upload_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryBatchUploadRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Inventory Batch Upload Inventory Batch Upload Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inventory/process:
    post:
      tags:
      - inventory
      summary: Inventory Process
      operationId: inventory_process_inventory_process_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryProcessRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Inventory Process Inventory Process Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inventory/images:
    get:
      tags:
      - inventory
      summary: Inventory Images
      operationId: inventory_images_inventory_images_get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 50
          title: Limit
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          default: 0
          title: Offset
      - name: processed
        in: query
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Processed
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Inventory Images Inventory Images Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inventory/items:
    get:
      tags:
      - inventory
      summary: Inventory Items
      operationId: inventory_items_inventory_items_get
      parameters:
      - name: image_id
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Image Id
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 50
          title: Limit
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          default: 0
          title: Offset
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Inventory Items Inventory Items Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inventory/stats:
    get:
      tags:
      - inventory
      summary: Inventory Stats
      operationId: inventory_stats_inventory_stats_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Inventory Stats Inventory Stats Get
  /feedback:
    post:
      tags:
      - feedback
      summary: Feedback
      operationId: feedback_feedback_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /garments/ingest:
    post:
      tags:
      - ingest
      summary: Garments Ingest
      description: 'Ingest a garment with an image (base64) and optional attributes.


        Returns garment_id and external_id. If the external_id was previously ingested,
        the

        existing id is returned (idempotent).'
      operationId: garments_ingest_garments_ingest_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Garments Ingest Garments Ingest Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /:
    get:
      summary: Read Root
      operationId: read_root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /admin/cache/clear:
    post:
      summary: Clear Caches
      operationId: clear_caches_admin_cache_clear_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Clear Caches Admin Cache Clear Post
components:
  schemas:
    FeedbackRequest:
      properties:
        user_id:
          type: string
          title: User Id
        garment_id:
          type: integer
          title: Garment Id
        action:
          type: string
          title: Action
        weight:
          anyOf:
          - type: number
          - type: 'null'
          title: Weight
        negative:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Negative
      type: object
      required:
      - user_id
      - garment_id
      - action
      title: FeedbackRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    IngestRequest:
      properties:
        external_id:
          type: string
          title: External Id
        image_base64:
          type: string
          title: Image Base64
        attributes:
          anyOf:
          - additionalProperties:
              items:
                type: string
              type: array
            type: object
          - type: 'null'
          title: Attributes
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        brand:
          anyOf:
          - type: string
          - type: 'null'
          title: Brand
        price:
          anyOf:
          - type: number
          - type: 'null'
          title: Price
        currency:
          anyOf:
          - type: string
          - type: 'null'
          title: Currency
      type: object
      required:
      - external_id
      - image_base64
      title: IngestRequest
    InventoryBatchUploadRequest:
      properties:
        items:
          items:
            $ref: '#/components/schemas/InventoryUploadRequest'
          type: array
          title: Items
        overwrite:
          type: boolean
          title: Overwrite
          default: false
      type: object
      required:
      - items
      title: InventoryBatchUploadRequest
    InventoryProcessRequest:
      properties:
        image_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Image Id
        overwrite:
          type: boolean
          title: Overwrite
          default: false
        model:
          anyOf:
          - type: string
          - type: 'null'
          title: Model
        limit:
          anyOf:
          - type: integer
          - type: 'null'
          title: Limit
      type: object
      title: InventoryProcessRequest
    InventoryUploadRequest:
      properties:
        filename:
          type: string
          title: Filename
        image_base64:
          type: string
          title: Image Base64
        overwrite:
          type: boolean
          title: Overwrite
          default: false
      type: object
      required:
      - filename
      - image_base64
      title: InventoryUploadRequest
    PreferenceExtractRequest:
      properties:
        conversation:
          type: string
          title: Conversation
        model:
          anyOf:
          - type: string
          - type: 'null'
          title: Model
      type: object
      required:
      - conversation
      title: PreferenceExtractRequest
    RefreshDescriptionRequest:
      properties:
        garment_id:
          type: integer
          title: Garment Id
        model:
          anyOf:
          - type: string
          - type: 'null'
          title: Model
        overwrite:
          type: boolean
          title: Overwrite
          default: false
      type: object
      required:
      - garment_id
      title: RefreshDescriptionRequest
    SearchRequest:
      properties:
        query:
          type: string
          title: Query
        limit:
          anyOf:
          - type: integer
          - type: 'null'
          title: Limit
          default: 10
        model:
          anyOf:
          - type: string
          - type: 'null'
          title: Model
        user_id:
          anyOf:
          - type: string
          - type: 'null'
          title: User Id
      type: object
      required:
      - query
      title: SearchRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
